variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch

stages:
  - build
  - test

before_script:
 - docker info

build:
  image: docker:dind
  stage: build
  cache:
    key: $CI_PROJECT_ID
    paths:
      - /root/
  script:
    - docker build -t $CI_PROJECT_PATH_SLUG .
  tags:
    - docker
    - xiliu


test:
  image: 
    name: $CI_PROJECT_PATH_SLUG
    entrypoint: [""]
  cache:
    key: $CI_PROJECT_ID
    paths:
      - /root/
  before_script:
    - which pip
    - find $(python -c "from pip._internal.utils.appdirs import user_cache_dir;print(user_cache_dir('pip'))") -maxdepth 2 || true
    - echo $PWD, $HOSTNAME
    - find /builds/  -maxdepth 2 || true
    - ln -s $PWD /data/code
    - find -L /data/code  -maxdepth 3 || true
    - echo C_FORCE_ROOT=true > .env
  stage: test
  script:
    - echo -e "from .base import *  \x23 NOQA\nDATABASES = {}" > src/etc/settings/ci.py
    - echo print\(\"OK\"\) | DJANGO_SETTINGS_MODULE=etc.settings.ci python src/manage.py shell
    - pip install flake8
    - flake8 --ignore F401,C901,F841,E401,E402,E501,W504
    - DJANGO_SETTINGS_MODULE=etc.settings.ci python src/manage.py test libs
  when: always
  tags:
    - docker

