version: "3"

services:
  redis:
    image: redis:3.2
    ports:
      - "6378:6379"
    volumes:
      - ./redis/conf:/usr/local/etc/redis/
      - ./redis/data:/data
      - ./redis/log:/data/log
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    container_name: backend_redis

  service:
    build: .
    volumes:
      - .:/data/code/
    ports:
      - "8589:8589"
    env_file:
      - ./.env
    container_name: backend_service





